services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    expose:
      - 27017
      
  voice_collector:
    build: ./voice_collector
    ports:
      - "5001:5001"
    depends_on:
      - "mongodb"

  voice_api:
    ports:
      - "5002:5002"
    build: ./voice_api
    depends_on:
      - "mongodb"
